### ISSUE TITLE
Commenting on the Seurat>Monocle data-analysis outlined in various Repos

### ISSUE THREAD

**Issue by Dragonmasterx87** [sneddonucsf/2018-Developmental-single-cell-RNA-sequencing#1]
Whoever the **Computational Biologist** was who wrote the codes [here](https://github.com/sneddonucsf/2018-Developmental-single-cell-RNA-sequencing/blob/182071d4d43602fab6e9edc5661a96a8316878ae/prepare_for_monocle_v1.R) and [here](https://github.com/sneddonucsf/2018-Developmental-single-cell-RNA-sequencing/blob/182071d4d43602fab6e9edc5661a96a8316878ae/monocle_seurat_input_v1.R) Deserves [this](https://en.wikipedia.org/wiki/Cookie). Whoever you are, we need more people like you on this planet.

**Comment by sneddonucsf** [comment]
Glad it was useful for you!
